---
- name: Vagrant ubuntu setup playbook
  hosts: all
  become: true
  tasks:
  - name: Update packages
    apt: upgrade=dist update_cache=yes

  - name: Install packages
    apt: name="{{ item }}" state=present
    with_items:
      - vim
      - python-pip
